### ISSUE TITLE
Cannot override LatexCommandSignature defaults from user config currently

### ISSUE THREAD

**Issue by zertrin** [valentjn/languagetool-languageserver#27]
Hi,

**Short version**
I would like to be able to override the default action for a `LatexCommandSignature` but currently, because default actions are listed first in the possible command list, is seems that the hard-coded action takes precedence over the user-defined one.

**Detailed analysis with references to code locations**

1. Default actions for `LatexCommandSignature` are defined here (example line): https://github.com/valentjn/ltex-ls/blob/04282cdd601764a6e771791900a625b4f2ee4df6/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilderDefaults.java#L292

1. This list of defaults is used to initiate the `commandSignatures` and `commandSignatureMap` in `LatexAnnotatedTextBuilder` here https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L92

1. Then the user settings are parsed and user-provided commands are **appended** to the list of commands here https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L924 and here https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L929

1. Later, the list of possible `possibleCommandSignatures` is retrieved here: https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L670

1. Then `possibleCommandSignatures` is iterated over to find the best match: https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L678

1. If a more precise match is found, then it is retained as the best candidate. But if multiple "best matches" are in the `possibleCommandSignatures` list, then only the **first** one will be used. Due to the construction of the list, the first one is the default hard-coded value, while the user-defined one would have come after.

**Proposed changes**

There are 2 possible solutions to allow the user-defined one to "win":
- change the `if` clause at https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L681 to `if (curMatch.length() >= match.length()) {` (changed the `>` to `>=` such that equal matches result in the last one being chosen)
- or change the way the user-provided commands are inserted into the list here https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L925 and https://github.com/valentjn/ltex-ls/blob/dc4aba4f05739ecf26e72c8da5fb79aeaad99e6e/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilder.java#L930 to `this.commandSignatures.add(0, new LatexCommandSignature([...]));` such that they are inserted at the beginning instead of the end of the list, thus will win later on.

What do you think? (personally, I believe the first solution (`>=`) is better)

PS: I don't have a Java development environment to test any of these deductions and possible solutions. I hope my code-reading was accurate, but I won't be able to open a pull request myself, sorry.

**Comment by valentjn** [comment]
Thanks for the suggestion. You can still open PRs even if you don't have a Java development environment: Just add a failing (at first) test for the desired feature and add your feature to get the tests running. ~Jenkins~ Travis should do everything for you.

**Comment by zertrin** [comment]
Thanks!

TBH, I didn't really look at the tests until now 🙄. I can read plain Java code for the main logic well enough, but without knowing the test framework used, I wouldn't have dared crafting a PR directly in GitHub 😄.

But the example from the commit (https://github.com/valentjn/ltex-ls/commit/101c2a7a2785b6fd5cd9d6365bd1b67ab59ef0a9) is useful and points me to the direction to understand it better. I might be able to directly propose a PR for small fixes in the future 😉

**Comment by valentjn** [comment]
Fix released in 8.0.0.

**Comment by Jieli12** [comment]
It seems that I still can't reset the customer setting for latex command. I disabled all extensions except latex workshop and ltex.  For example, I want to ignore this latex command **\lstset{style=mylststyle}**. In the settings.json file, I add
`"ltex.latex.commands": {
    "\\\\lstset{}": "ignore"
  }`
But It doesn't work, would you please help me to solve this problem?
